### ISSUE TITLE
Map and buildings not migrating from 2.2 to 2.3

### ISSUE THREAD

**Issue by Naturalien** [gloomhaven-tts-enhanced/public-scripts#82]
When transfering the campaign from 2.2 to 2.3 via the save token the map does not load. When I first start a new campaign and then load the map, the map is there. But it does not have the correct stickers on it and the buildings are not updated. Neither the unlocked scenarios are loaded.
![image](https://github.com/user-attachments/assets/0719a7c9-dab6-4207-ae3f-e73e9633afe7)

Btw I checked the .json of the markers and the buildings are just missing. They do not get saved:

How it should look:
![image](https://github.com/user-attachments/assets/5a346846-7a43-4eff-93d8-f698f8199ae6)
[session2_middle.json](https://github.com/user-attachments/files/18132493/session2_middle.json)

How it looks:
![image](https://github.com/user-attachments/assets/6d95e14d-1fcb-43fe-9c29-2b3f07224122)
[sess.json](https://github.com/user-attachments/files/18132495/sess.json)

**Comment by Naturalien** [comment]
Btw I checked the .json of the markers and the buildings are just missing. They do not get saved:

How it should look:
![image](https://github.com/user-attachments/assets/5a346846-7a43-4eff-93d8-f698f8199ae6)

How it looks:
![image](https://github.com/user-attachments/assets/6d95e14d-1fcb-43fe-9c29-2b3f07224122)

**Comment by Sebaestschjin** [comment]
Could you please share the save file you are migrating from? Are there any errors while creating the migration file?

**Comment by Naturalien** [comment]
Thank you for your quick reply!

Here is the savegame (at least I think it is the latest one). It is not creating the map data for quite a while now, so its not just this single save game but its the case since several sessions ago:
[TS_Save_191.zip](https://github.com/user-attachments/files/18135367/TS_Save_191.zip)

This is the output when creating the token:
![image](https://github.com/user-attachments/assets/ce0b8b50-3118-45de-bf1e-044de7a6fa39)

Loading the token throws no errors at all: 
![image](https://github.com/user-attachments/assets/f19cf398-3a5d-40d3-81d8-2b76b4df9bcd)

**Comment by Sebaestschjin** [comment]
Ah, yeah, this is a known bug with the 2.2 version. There's a short guide here: https://gloomhaven-tts-enhanced.github.io/public-scripts/mod/latest/frosthaven/missingFeatures.html#invalid-sort-order
This should make the error while creating the save go away and make the save file complete.

**Comment by Naturalien** [comment]
> Ah, yeah, this is a known bug with the 2.2 version. There's a short guide here: https://gloomhaven-tts-enhanced.github.io/public-scripts/mod/latest/frosthaven/missingFeatures.html#invalid-sort-order This should make the error while creating the save go away and make the save file complete.

I didn't know! Thanks a lot. I will try this later or tomorrow. If it doesn't work I will give further feedback.

**Comment by Naturalien** [comment]
It did work! Thanks alot for your support!

![image](https://github.com/user-attachments/assets/bdc2a597-dbde-4af2-8139-4001399fb3ce)
